# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: pmb2_arm
  joint_model_group_pose: travelling_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - caster_back_left_1_joint
    - caster_back_left_2_joint
    - caster_back_right_1_joint
    - caster_back_right_2_joint
    - caster_front_left_1_joint
    - caster_front_left_2_joint
    - caster_front_right_1_joint
    - caster_front_right_2_joint
    - palbator_arm_column_joint
    - palbator_arm_shoulder_1_joint
    - palbator_arm_shoulder_2_joint
    - palbator_arm_shoulder_3_joint
    - palbator_arm_wrist_1_joint
    - palbator_arm_wrist_2_joint
    - palbator_arm_wrist_3_joint
    - motor1_hand_joint
    - hand1_fingertip1_joint
    - hand1_fingertip2_joint
    - motor2_hand_joint
    - hand2_fingertip1_joint
    - hand2_fingertip2_joint
    - suspension_left_joint
    - wheel_left_joint
    - suspension_right_joint
    - wheel_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: pmb2_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - palbator_arm_shoulder_1_joint
      - palbator_arm_shoulder_2_joint
      - palbator_arm_shoulder_3_joint
      - palbator_arm_wrist_1_joint
      - palbator_arm_wrist_2_joint
      - palbator_arm_wrist_3_joint
  - name: pmb2_column_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - palbator_arm_column_joint
  - name: pmb2_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - motor1_hand_joint
      - motor2_hand_joint