pmb2_arm_controller:
# Publish all joint states -----------------------------------

# Position Controllers ---------------------------------------

  # joint1_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: shoulder_1_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}

  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: shoulder_2_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}

  # arm_column_link_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_column_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}

  # arm_shoulder_link_1_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_shoulder_1_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}
  
  # arm_shoulder_link_2_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_shoulder_2_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}
  
  # arm_shoulder_link_3_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_shoulder_3_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}
  
  # arm_wrist_link_1_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_wrist_1_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}

  # arm_wrist_link_2_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_wrist_2_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}

  # arm_wrist_link_3_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: palbator_arm_wrist_3_joint
  #   pid: {p: 10.0, i: 0.0, d: 0.1}


# Trajectory Controllers --------------------------------------

  arm_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - palbator_arm_column_joint
      - palbator_arm_shoulder_1_joint
      - palbator_arm_shoulder_2_joint
      - palbator_arm_shoulder_3_joint
      - palbator_arm_wrist_1_joint
      - palbator_arm_wrist_2_joint
      - palbator_arm_wrist_3_joint
      # - palbator_arm_end_link
    constraints:
      goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0
      palbator_arm_column_joint: {trajectory: 0.1, goal: 0.1}
      palbator_arm_shoulder_1_joint: {trajectory: 0.1, goal: 0.1}
      palbator_arm_shoulder_2_joint: {trajectory: 0.1, goal: 0.1}
      palbator_arm_shoulder_3_joint: {trajectory: 0.1, goal: 0.1}
      palbator_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      palbator_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      palbator_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}

    gains: # Required because we're controlling an effort interface
      # shoulder_1_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 0}
      # shoulder_2_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 0}
      palbator_arm_column_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
      palbator_arm_shoulder_1_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
      palbator_arm_shoulder_2_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
      palbator_arm_shoulder_3_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
      palbator_arm_wrist_1_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
      palbator_arm_wrist_2_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
      palbator_arm_wrist_3_joint: {p: 100,  d: 5, i: 2, i_clamp: 2}
    
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    
      
